spring.application.name=department-service

## This line tells the application to import configuration properties from a Config Server running at the specified URL.
# The "optional:" prefix means that if the Config Server is not available, the application will still start with default properties.

spring.config.import=optional:configserver:http://localhost:8888

## The following lines are commented out because we are using the Config Server to manage these properties.
# You can uncomment them if you want to run the application without the Config Server.

#server.port=8085
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/departmentdb
#spring.datasource.username=postgres
#spring.datasource.password=root
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#eureka.instance.client.service-url.defaultZone=http://localhost:8761/eureka/


#management.endpoints.web.exposure.include=*
#
### Add RabbitMQ properties if you are using RabbitMQ for messaging
#
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#
### Distributed tracing configuration for micrometer and Zipkin
#
#management.tracing.enabled=true
#management.tracing.sampling.probability=1.0
#
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId},%X{spanId}]
