spring.application.name=employee-service

## This line tells the application to import configuration properties from a Config Server running at the specified URL.
# The "optional:" prefix means that if the Config Server is not available, the application will still start with default properties.

spring.config.import=optional:configserver:http://localhost:8888

#spring.datasource.url=jdbc:postgresql://localhost:5432/employeedb
#spring.datasource.username=postgres
#spring.datasource.password=root
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#server.port=8086
#
#eureka.instance.client.service-url.defaultZone=http://localhost:8761/eureka/

#management.endpoints.web.exposure.include=*

## Add rabbitmq properties if you are using RabbitMQ for messaging

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

## Distributed tracing configuration for micrometer and Zipkin

#management.tracing.enabled=true
#management.tracing.sampling.probability=1.0
#
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId},%X{spanId}]


## Circuit breaker configuration for resilience4j
#management.health.circuitbreakers.enabled=true
#management.endpoint.health.show-details=always
#resilience4j.circuitbreaker.instances.employee-service.registerHealthIndicator=true
#resilience4j.circuitbreaker.instances.employee-service.failureRateThreshold=50
#resilience4j.circuitbreaker.instances.employee-service.minimumNumberOfCalls=5
#resilience4j.circuitbreaker.instances.employee-service.automaticTransitionFromOpenToHalfOpenEnabled=true
#resilience4j.circuitbreaker.instances.employee-service.waitDurationInOpenState=5s
#resilience4j.circuitbreaker.instances.employee-service.permittedNumberOfCallsInHalfOpenState=3
#resilience4j.circuitbreaker.instances.employee-service.slidingWindowSize=10
#resilience4j.circuitbreaker.instances.employee-service.slidingWindowType=COUNT_BASED

## Retry configuration for resilience4j
#resilience4j.retry.instances.employee-service.maxRetryAttempts=5
#resilience4j.retry.instances.employee-service.waitDuration=1s
#resilience4j.retry.instances.employee-service.registerHealthIndicator=true